export const rentas = [
  {
    id: 1,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 2,
    usuario: "Juanito Pérez",
    vehiculo: "Susuki",
    estado: "terminado",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 3,
    usuario: "Abelardo Gutiérrez",
    vehiculo: "Nissan",
    estado: "cancelado",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 4,
    usuario: "Juanito Pérez",
    vehiculo: "UltraMegaSusuki",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 5,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$1,528.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 6,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$48.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 7,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 2",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 8,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$145.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 9,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 5",
    estado: "cancelado",
    monto: "$49.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 10,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 11,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 6",
    estado: "terminado",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 12,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$42.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 13,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
  {
    id: 14,
    usuario: "Juanito Pérez",
    vehiculo: "Ford 1",
    estado: "activo",
    monto: "$45.00",
    fechaInicio: "04/09/2023",
    fechaFin: "10/09/2023",
  },
];

export const vehiculos = [
  {
    id: 1,
    name: "Toyota ",
    model: "Corolla",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "El sedán más vendido de Toyota.",
    price: "30",
    image: " ",
  },
  {
    id: 2,
    name: "Ford",
    model: "Escape",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "automática",
    description: "Una SUV versátil para la ciudad y la carretera.",
    price: "40",
    image: " ",
  },
  {
    id: 3,
    name: "Chevrolet ",
    model: "Trailblazer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV espaciosa y cómoda para la familia.",
    price: "40",
    image: " ",
  },
  {
    id: 4,
    name: "Honda ",
    model: "Civic",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un clásico en el segmento de los sedanes compactos.",
    price: "30",
    image: " ",
  },
  {
    id: 5,
    name: "Renault",
    model: "Duster",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "manual",
    description: "Una SUV asequible para aventuras todoterreno.",
    price: "40",
    image: " ",
  },
  {
    id: 6,
    name: "Volkswagen",
    model: "Amarok",
    year: 2023,
    type: "camioneta",
    capacity: 5,
    transmission: "automática",
    description: "Una potente camioneta para el trabajo y el ocio.",
    price: "50",
    image: " ",
  },
  {
    id: 7,
    name: "Toyota Camry",
    model: "Camry",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un sedán elegante y confortable.",
    price: "30",
    image: " ",
  },
  {
    id: 8,
    name: "Ford ",
    model: "Explorer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV grande y espaciosa para la familia.",
    price: "40",
    image: " ",
  },
  {
    id: 9,
    name: "Toyota ",
    model: "Corolla",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "El sedán más vendido de Toyota.",
    price: "30",
    image: " ",
  },
  {
    id: 10,
    name: "Ford",
    model: "Escape",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "automática",
    description:
      "Una SUV versátil para la ciudad y la carretera. Increíble para largos viajes y aventuras.",
    price: "40",
    image: " ",
  },
  {
    id: 11,
    name: "Chevrolet ",
    model: "Trailblazer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV espaciosa y cómoda para la familia.",
    price: "40",
    image: " ",
  },
  {
    id: 12,
    name: "Honda ",
    model: "Civic",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un clásico en el segmento de los sedanes compactos.",
    price: "30",
    image: " ",
  },
  {
    id: 13,
    name: "Renault",
    model: "Duster",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "manual",
    description: "Una SUV asequible para aventuras todoterreno.",
    price: "40",
    image: " ",
  },
  {
    id: 14,
    name: "Volkswagen",
    model: "Amarok",
    year: 2023,
    type: "camioneta",
    capacity: 5,
    transmission: "automática",
    description: "Una potente camioneta para el trabajo y el ocio.",
    price: "50",
    image: " ",
  },
  {
    id: 15,
    name: "Toyota Camry",
    model: "Camry",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un sedán elegante y confortable.",
    price: "30",
    image: " ",
  },
  {
    id: 16,
    name: "Ford ",
    model: "Explorer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV grande y espaciosa para la familia.",
    price: "40",
    image: " ",
  },
  {
    id: 17,
    name: "Toyota ",
    model: "Corolla",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "El sedán más vendido de Toyota.",
    price: "30",
    image: " ",
  },
  {
    id: 18,
    name: "Ford",
    model: "Escape",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "automática",
    description: "Una SUV versátil para la ciudad y la carretera.",
    price: "40",
    image: " ",
  },
  {
    id: 19,
    name: "Chevrolet ",
    model: "Trailblazer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV espaciosa y cómoda para la familia.",
    price: "40",
    image: " ",
  },
  {
    id: 20,
    name: "Honda ",
    model: "Civic",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un clásico en el segmento de los sedanes compactos.",
    price: "30",
    image: " ",
  },
  {
    id: 21,
    name: "Renault",
    model: "Duster",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "manual",
    description: "Una SUV asequible para aventuras todoterreno.",
    price: "40",
    image: " ",
  },
  {
    id: 22,
    name: "Volkswagen",
    model: "Amarok",
    year: 2023,
    type: "camioneta",
    capacity: 5,
    transmission: "automática",
    description: "Una potente camioneta para el trabajo y el ocio.",
    price: "50",
    image: " ",
  },
  {
    id: 23,
    name: "Toyota Camry",
    model: "Camry",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un sedán elegante y confortable.",
    price: "30",
    image: " ",
  },
  {
    id: 24,
    name: "Ford ",
    model: "Explorer",
    year: 2023,
    type: "SUV",
    capacity: 7,
    transmission: "automática",
    description: "Una SUV grande y espaciosa para la familia.",
    price: "40",
    image: " ",
  },
];

export const vehiculosBorrados = [
  {
    id: 20,
    name: "Honda ",
    model: "Civic",
    year: 2023,
    type: "sedán",
    capacity: 5,
    transmission: "automática",
    description: "Un clásico en el segmento de los sedanes compactos.",
    price: "30",
    image: " ",
  },
  {
    id: 21,
    name: "Renault",
    model: "Duster",
    year: 2023,
    type: "SUV",
    capacity: 5,
    transmission: "manual",
    description: "Una SUV asequible para aventuras todoterreno.",
    price: "40",
    image: " ",
  },
  {
    id: 22,
    name: "Volkswagen",
    model: "Amarok",
    year: 2023,
    type: "camioneta",
    capacity: 5,
    transmission: "automática",
    description: "Una potente camioneta para el trabajo y el ocio.",
    price: "50",
    image: " ",
  },
];

export const usuariosBorrados = [
  {
    id: 1,
    correo: "correo1@correo.com",
    nombre: "Juanito Uno",
    pasaporte: 123451,
    reservas: [
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "cancelado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
    ],
  },
  {
    id: 2,
    correo: "correo2@correo.com",
    nombre: "Juanito Dos",
    pasaporte: 123452,
    reservas: [
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "cancelado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
    ],
  },
  {
    id: 3,
    correo: "correo3@correo.com",
    nombre: "Juanito Tres",
    pasaporte: 123453,
    reservas: [
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "cancelado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
    ],
  },
  {
    id: 4,
    correo: "correo4@correo.com",
    nombre: "Juanito Cuatro",
    pasaporte: 123454,
    reservas: [
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "cancelado",
      },
      {
        vehiculo: "Ford1",
        fechaInicio: "1996/27/05",
        fechaFin: "1996/27/25",
        estado: "finalizado",
      },
    ],
  },
];
