import { Providers } from "../store/providers";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer";
import { store } from "@/store";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
const inter = Inter({ subsets: ["latin"] });
import Loading from "./loading";
import { Suspense } from "react";
import Chat from "@/components/Chat";

export const metadata = {
  title: "Auto Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Providers store={store}>
            <Navbar />
            <Suspense fallback={<Loading />}>{children}</Suspense>
            <Chat />
            <Footer />
          </Providers>
        </AuthContextProvider>
      </body>
    </html>
  );
}
